### ISSUE TITLE
Modify dangerous delete command

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-build-tools#196]
In the task `Delete existing icons from ~{{ros_user}}` everything is deleted from the Desktop. This is quite dangerous, unless we use this strictly with new installs.

https://github.com/shadow-robot/sr-build-tools/blob/master/ansible/roles/ros_user/tasks/main.yml#L36

Maybe we should delete only the icons?

**Comment by ugocupcic** [comment]
It's a setup script for a production machine. I wanted to have control over the desktop. 

I was thinking of creating a dev machine script that would be less disruptive (no new user creation, no desktop cleansing, etc...).

**Comment by toliver** [comment]
Sounds sensible. Let's make sure we all know about that.
Would a prompt message in the beginning of the process asking for confirmation make sense?
