### ISSUE TITLE
dev-machine not installing deps

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-build-tools#211]
When installing a dev-machine using [this script](bit.ly/dev-machine), dependencies are not installed for the `base` ws, only for the `base_deps` ws.

**Comment by ugocupcic** [comment]
It's supposed to install both (https://github.com/shadow-robot/sr-build-tools/blob/master/ansible/roles/ros_workspace/tasks/main.yml#L137-L150). 

Double checking
