### ISSUE TITLE
delete warehouse ros from .rosinstall

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/sr-build-tools#223]
otherwise wstool up grabs it again.

**Comment by dg-shadow** [comment]
Does this task complete the removal of the source warehouse_ros from the setup scripts?

**Comment by ugocupcic** [comment]
It removes the workspace hacks (you know overlay warehouse over the normal workspace, recompile etc...). Removing warehouse_ros from the repository.rosinstall should be handled in the relevant repos.

**Comment by ugocupcic** [comment]
Fixed by #226
