### ISSUE TITLE
Add warning to new computer - production checklist

### ISSUE THREAD

**Issue by toliver** [shadow-robot/sr-build-tools#224]
The main [instructions](http://sr-build-tools.readthedocs.org/en/latest/README/), are pointing to the install of a [production machine](http://sr-build-tools.readthedocs.org/en/latest/Production%20Checklist/).

I think that is correct, but maybe we should add a warning that the production machine script is not intended to be used to set up a development environment, and specially that it will create a new linux user, which might be undesirable for some people.

**Comment by ugocupcic** [comment]
The [install instructions](http://shadow-robot.readthedocs.org/en/latest/generated/shadow_robot/INSTALL.html) are pointing to the dev script. The instructions you point to are the production checklist. 

Still a good idea to add that warning.
