### ISSUE TITLE
Fix testing procedure documentation

### ISSUE THREAD

**Issue by AndriyPt** [shadow-robot/sr-build-tools#279]
Please do following fixes in https://github.com/shadow-robot/sr-build-tools/blob/master/documentation/test_procedure.md

- use bold for docker commands during enumeration and explanation in this section https://github.com/shadow-robot/sr-build-tools/blob/master/documentation/test_procedure.md#docker
- in section https://github.com/shadow-robot/sr-build-tools/blob/master/documentation/test_procedure.md#testing-master-branches full command for development script is not visualized. There is only CURL part
- change the whole section https://github.com/shadow-robot/sr-build-tools/blob/master/documentation/test_procedure.md#using-x-with-docker . For full UI testing we'll recommend to use virtual machine.

**Comment by toliver** [comment]
This document seems focused on testing the one-liners, if that is the case maybe it should be clear in the title.

Also please change the docker section so that it points to a plain Ubuntu container. This is necessary to test the one-liners.

```bash
sudo docker pull ubuntu:14.04.4
sudo docker run -it --name "ubuntu_trusty" "ubuntu:14.04.4" /bin/bash
```
