### ISSUE TITLE
Clean up sync mess (sr_utils)

### ISSUE THREAD

**Issue by markpitchless** [shadow-robot/sr-build-tools#88]
When a new repo gets added but not added to the trello team on github, the sync keeps adding cards over and over to backlog. sr_utils 1 and 2 have done this. No multi select in trello so need a quick clean up script.

**Comment by fr33dr4g0n** [comment]
Theres an app using the Trello API that allows multi select (delete, label etc). You can find it here: https://foreach.meteor.com/Trello and read about it on the official Trello development board: https://trello.com/c/DVwrtOzV/1367-multi-select.

The dude who's developing it also adds features within minutes, just hop on the chat and tell him that you need some thing.
